### ISSUE TITLE
Fix NPE after invoking failLastTest

### ISSUE THREAD

**Issue by Grigory-Rylov** [Grigory-Rylov/android-instrumental-test-runner-core#73]
`Caused by: java.lang.NullPointerException
	at com.github.grishberg.tests.commands.reports.xml.CustomTestRunListener.testFailed(CustomTestRunListener.java:96)
	at com.github.grishberg.tests.commands.reports.TestXmlReportsGenerator.testFailed(TestXmlReportsGenerator.java:66)
	at com.github.grishberg.tests.commands.reports.TestXmlReportsGenerator.failLastTest(TestXmlReportsGenerator.java:77)
	at com.github.grishberg.tests.commands.SingleInstrumentalTestCommand.executeImpl(SingleInstrumentalTestCommand.java:161)
	at com.github.grishberg.tests.commands.SingleInstrumentalTestCommand.execute(SingleInstrumentalTestCommand.java:187)`

**Comment by sabahmax-dev** [comment]
Thanks for reporting this. I’ve opened PR #84 to fix the NPE that can occur after invoking `failLastTest`. It prevents a null failed-test state from reaching the XML report listener, so the test report no longer crashes in this case.
